### ISSUE TITLE
Loggie Geek Camp 火爆启动 欢迎参与

### ISSUE THREAD

**Issue by ethfoo** [loggie-io/loggie#203]
本次 Loggie Geek Camp 活动为期五周，截止6月中旬，包含提供 User Case、捕捉 Bug、完善和提交 Feature 等四类任务，表现优异者将可获得网易数帆及 Loggie 社区表彰。

详情请戳：[Loggie geek camp](https://sf.163.com/loggie)

#### A. 提供User Case： 

提供你对 Loggie 的使用方式，帮助Loggie找到并适配更多的应用场景，请加Loggie Bot并提供材料即可。

#### B. 捕捉Bug：

发现并提交一个或以上 Loggie 的 Bug，或者是被我们忽略的体验问题，请提issues即可。
 
#### C. 完善文档：

在 Loggie 使用过程中，觉得有文档上的缺失？欢迎补充你的想法。
请给 [Loggie docs](https://github.com/loggie-io/docs) 提PR即可。

#### D. 提交Feature：

为 Loggie 的功能添砖加瓦。

这里我们提供了一些feature供你选择，按照size分为不同的难度级别，当然你也可以在这之外创建自己的想要贡献的功能issues并在下面留言，我们确认后即可。

**Feature:**

[size/XXL]
- [ ] [Support Clickhouse sink](https://github.com/loggie-io/loggie/issues/200)
- [ ] [Support Pulsar sink](https://github.com/loggie-io/loggie/issues/199)
- [ ] [Support Elasticsearch source](https://github.com/loggie-io/loggie/issues/198)

[size/XL]
- [ ] [Monitoring listener for normalize interceptor](https://github.com/loggie-io/loggie/issues/197)
- [ ] [Dynamic matching topic in kafka source](https://github.com/loggie-io/loggie/issues/196)
- [ ] [Add grok processor in normalize interceptor](https://github.com/loggie-io/loggie/issues/195)

[size/L]
- [ ] [kafka source 添加认证功能](https://github.com/loggie-io/loggie/issues/194)
- [ ] [Sink dev for abnormal test scenarios](https://github.com/loggie-io/loggie/issues/193)
- [ ] [Support any data content and lasting period in dev source](https://github.com/loggie-io/loggie/issues/192)

### 

参与活动，加入活动微信群，以及任何问题，请加Loggie Bot：

![image](https://user-images.githubusercontent.com/3616466/168582707-12bac146-45c8-4cd3-916c-b25df5c56994.png)
